### ISSUE TITLE
"Error: Process completed with exit code 1" issue on Github Action.

### ISSUE THREAD

**Issue by metrue** [yandex/gixy#124]
I keep getting failed with following log in Github Action run. 
```
Run gixy -lll data/nginx/app.conf
  gixy -lll data/nginx/app.conf
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.0/x64/lib
[nginx_parser]	ERROR	Failed to parse config "/home/runner/work/gateway/gateway/data/nginx/app.conf": char 9 (line:1, col:10)

==================== Results ===================
No issues found.

==================== Summary ===================
Total issues:
    Unspecified: 0
    Low: 0
    Medium: 0
    High: 0

Error: Process completed with exit code 1.
```

and my actions defined like this,
```yaml
name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install gixy
        run: |
          pip install gixy
      - name: check nginx config
        run: |
          gixy -lll data/nginx/app.conf
```
